# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b9e77d50c9850e1a2c9e295b679009b4253582fb77dcc4daba7fac72666cfffb53144997ecc7b38a3200837a78d0247e03c8e412eb341c070a965e12c60e247

test:
  secret_key_base: 2f7f752d280148b0e1b10061eed12568263e3859539f2e53a805a4cb9d2470c5daaa1d095027fd735c30b65634e46f84d002a97e54b6c65ddfece2f859170564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
